articles/urls.py
from django.urls import path
from . import views
app_name='articles'
urlpatterns = [
    path('',views.blogs, name='blogs'),
    path('<int:id>',views.blog_detail, name='blog-detail'),
    path('my-blogs',views.my_blogs, name='my-blogs'),
    path('add-blog',views.add_blog, name='add-blog'),
    path('edit-blog/<int:id>',views.edit_blog, name='edit-blog'),
]

info/urls.py
from django.urls import path
from . import views

app_name='info'

urlpatterns = [
    path('',views.home, name='home'),
    path('products',views.shop, name='shop'),
    path('products/<int:id>',views.product_detail, name='product-detail'),
    path('products/compare',views.product_compare, name='product-compare'),
    path('contact',views.contact, name='contact'),
]

main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('articles/', include('articles.urls')),
    path('user/', include('user.urls')),
    path('user_interaction/', include('user_interaction.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Author(models.Model):
    user=models.OneToOneField(User,on_delete= models.CASCADE)
    bio=models.TextField()
    def __str__(self):
        return self.user.username

class Tag(models.Model):
    title=models.CharField(max_length=10)
    def __str__(self):
        return self.title

class Article(models.Model):
    title = models.CharField(max_length = 20,unique = True)
    description = models.TextField(null = True,blank = True)
    content = models.TextField()
    show = models.BooleanField(default = True)
    view_count = models.IntegerField(default = 0)
    image = models.ImageField(null = True, blank = True)
    created = models.DateField(auto_now_add = True)
    # author=models.ForeignKey(Author,on_delete=models.SET_NULL,null=True,blank=True)
    tags=models.ManyToManyField(Tag)

    def __str__(self):
        return self.title
    

class ArticleImage(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='article_images/')

articles/forms.py
from django import forms
from .models import Article




class ArticleForm(forms.ModelForm):
    class Meta:
        model=Article
        # fields='__all__'  
        exclude=['view_count','author']

    def save(self,author):
        instance=super().save()
        instance.author=author
        instance.save()
        return instance

articles/views.py
from django.shortcuts import render
from .models import Article, Author, Tag
from django.core.paginator import Paginator

def blogs(request):
    author_username = request.GET.get('author')
    articles = Article.objects.all() 
    authors = Author.objects.all()
    tags = Tag.objects.all()
    tag_title = request.GET.get('tag')
    page_number = int(request.GET.get('page', 1))
    if author_username:
        articles = articles.filter(author__user__username=author_username)
    if tag_title:
        articles = articles.filter(tags__title=tag_title)

    paginator = Paginator(articles, 3)
    page = paginator.page(page_number)
    articles = page.object_list

    return render(request, 'blogs.html', context={'articles': articles, 'authors': authors, 'tags': tags, 'paginator': paginator, 'page': page})
    





def blog_detail(request,id):
    article = Article.objects.get(id=id)
    return render(request, "blog-detail.html", context={'article': article})



def my_blogs(request):
    return render(request,'my-blogs.html')
def add_blog(request):
    return render(request,'add-blog.html')
def edit_blog(request,id):
    return render(request,'edit-blog.html')
    
    

articles/templates/blog-detail.html
{% extends "layout.html" %}
{% load static %}
{% block main %}


<!-- Mobile menu -->
<div class="cr-sidebar-overlay"></div>
<div id="cr_mobile_menu" class="cr-side-cart cr-mobile-menu">
    <div class="cr-menu-title">
        <span class="menu-title">My Menu</span>
        <button type="button" class="cr-close">×</button>
    </div>
    <div class="cr-menu-inner">
        <div class="cr-menu-content">
            <ul>
                <li class="dropdown drop-list">
                    <a href="index.html">Home</a>
                </li>
                <li class="dropdown drop-list">
                    <span class="menu-toggle"></span>
                    <a href="javascript:void(0)" class="dropdown-list">Category</a>
                    <ul class="sub-menu">
                        <li><a href="shop-left-sidebar.html">Shop Left sidebar</a></li>
                        <li><a href="shop-right-sidebar.html">Shop Right sidebar</a></li>
                        <li><a href="shop-full-width.html">Full Width</a></li>
                    </ul>
                </li>
                <li class="dropdown drop-list">
                    <span class="menu-toggle"></span>
                    <a href="javascript:void(0)" class="dropdown-list">product</a>
                    <ul class="sub-menu">
                        <li><a href="product-left-sidebar.html">product Left sidebar</a></li>
                        <li><a href="product-right-sidebar.html">product Right sidebar</a></li>
                        <li><a href="product-full-width.html">Product Full Width </a></li>
                    </ul>
                </li>
                <li class="dropdown drop-list">
                    <span class="menu-toggle"></span>
                    <a href="javascript:void(0)" class="dropdown-list">Pages</a>
                    <ul class="sub-menu">
                        <li><a href="about.html">About Us</a></li>
                        <li><a href="contact-us.html">Contact Us</a></li>
                        <li><a href="cart.html">Cart</a></li>
                        <li><a href="checkout.html">Checkout</a></li>
                        <li><a href="track-order.html">Track Order</a></li>
                        <li><a href="wishlist.html">Wishlist</a></li>
                        <li><a href="faq.html">Faq</a></li>
                        <li><a href="login.html">Login</a></li>
                        <li><a href="register.html">Register</a></li>
                        <li><a href="policy.html">Policy</a></li>
                    </ul>
                </li>
                <li class="dropdown drop-list">
                    <span class="menu-toggle"></span>
                    <a href="javascript:void(0)" class="dropdown-list">Blog</a>
                    <ul class="sub-menu">
                        <li><a href="blog-left-sidebar.html">Left Sidebar</a></li>
                        <li><a href="blog-right-sidebar.html">Right Sidebar</a></li>
                        <li><a href="blog-full-width.html">Full Width</a></li>
                        <li><a href="blog-detail-left-sidebar.html">Detail Left Sidebar</a></li>
                        <li><a href="blog-detail-right-sidebar.html">Detail Right Sidebar</a></li>
                        <li><a href="blog-detail-full-width.html">Detail Full Width</a></li>
                    </ul>
                </li>
                <li class="dropdown drop-list">
                    <span class="menu-toggle"></span>
                    <a href="javascript:void(0)">Element</a>
                    <ul class="sub-menu">
                        <li><a href="elements-products.html">Products</a></li>
                        <li><a href="elements-typography.html">Typography</a></li>
                        <li><a href="elements-buttons.html">Buttons</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<!-- Breadcrumb -->
<section class="section-breadcrumb">
    <div class="cr-breadcrumb-image">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="cr-breadcrumb-title">
                        <h2>Blog Details</h2>
                        <span> <a href="index.html">Home</a> - Blog Details</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Blog-details -->
<section class="blog-details padding-tb-100">
    <div class="container">
        <div class="row" data-aos="fade-up" data-aos-duration="2000" data-aos-delay="400">
            <div class="col-lg-12">
                <div class="cr-blog-details">
                    <div class="cr-blog-details-image">
                        <img src="{{article.image.url}}" alt="blog-1">
                    </div>
                    <div class="cr-blog-details-content">
                        <div class="cr-admin-date">
                            <span><code>By Admin</code> / 07 Comment / {{article.created}}</span>
                        </div>
                        <div class="cr-banner">
                            <h2>{{article.title}}</h2>
                        </div>
                        <p class="mb-15">{{article.description}}</p>
                        
                    </div>
                    <div class="row mt-30">
                        <div class="col-6">
                            <div class="cr-blog-inner-cols">
                                <div class="blog-img">
                                    <img src="assets/img/blog/blog-2.jpg" alt="blog-2">
                                </div>
                                <div class="cr-blog-inner-content">
                                    <p>Lorem ipsum dolor consectetur adipisicing elit. Molestias, dolorum!</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="cr-blog-inner-cols">
                                <div class="blog-img">
                                    <img src="assets/img/blog/blog-3.jpg" alt="blog-3">
                                </div>
                                <div class="cr-blog-inner-content">
                                    <p>Lorem ipsum dolor consectetur adipisicing elit. Molestias, dolorum!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="cr-blog-details-message">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat repellat earum
                            architecto odit soluta quas odio distinctio quae numquam? Quaerat nulla blanditiis
                            possimus quae. Iusto doloribus, est aliquam delectus pariatur voluptatem cum iste
                            exercitationem rem.</p>
                        <h5 class="title"> John martin</h5>
                    </div>
                    <div class="cr-blog-details-paragrap">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores officia magni
                            explicabo fuga molestiae architecto ipsa excepturi laudantium molestias, assumenda vel
                            fugiat hic exercitationem. Necessitatibus itaque et id! Ratione accusantium voluptatum
                            optio rerum facilis expedita.</p>
                    </div>
                    <div class="cr-blog-details-tags">
                        <div class="cr-details-tags">
                            <ul class="cr-tags blog">
                                <li><a href="javascript:void(0)">Cabbage</a></li>
                                <li><a href="javascript:void(0)">Appetizer</a></li>
                                <li><a href="javascript:void(0)">Meat Food</a></li>
                            </ul>
                            <div class="cr-logo">
                                <a href="javascript:void(0)"><i class="ri-facebook-line"></i></a>
                                <a href="javascript:void(0)"><i class="ri-twitter-x-line"></i></a>
                                <a href="javascript:void(0)"><i class="ri-instagram-line"></i></a>
                                <a href="javascript:void(0)"><i class="ri-linkedin-line"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <nav aria-label="..." class="cr-pagination">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">Previous</span>
                    </li>
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">1</span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</section>

{% endblock main %}

articles/templates/blogs.html
{% extends "layout.html" %}
{% load static %}
{% block main %}



    <!-- Mobile menu -->
    <div class="cr-sidebar-overlay"></div>
    <div id="cr_mobile_menu" class="cr-side-cart cr-mobile-menu">
        <div class="cr-menu-title">
            <span class="menu-title">My Menu</span>
            <button type="button" class="cr-close">×</button>
        </div>
        <div class="cr-menu-inner">
            <div class="cr-menu-content">
                <ul>
                    <li class="dropdown drop-list">
                        <a href="index.html">Home</a>
                    </li>
                    <li class="dropdown drop-list">
                        <span class="menu-toggle"></span>
                        <a href="javascript:void(0)" class="dropdown-list">Category</a>
                        <ul class="sub-menu">
                            <li><a href="shop-left-sidebar.html">Shop Left sidebar</a></li>
                            <li><a href="shop-right-sidebar.html">Shop Right sidebar</a></li>
                            <li><a href="shop-full-width.html">Full Width</a></li>
                        </ul>
                    </li>
                    <li class="dropdown drop-list">
                        <span class="menu-toggle"></span>
                        <a href="javascript:void(0)" class="dropdown-list">product</a>
                        <ul class="sub-menu">
                            <li><a href="product-left-sidebar.html">product Left sidebar</a></li>
                            <li><a href="product-right-sidebar.html">product Right sidebar</a></li>
                            <li><a href="product-full-width.html">Product Full Width </a></li>
                        </ul>
                    </li>
                    <li class="dropdown drop-list">
                        <span class="menu-toggle"></span>
                        <a href="javascript:void(0)" class="dropdown-list">Pages</a>
                        <ul class="sub-menu">
                            <li><a href="about.html">About Us</a></li>
                            <li><a href="contact-us.html">Contact Us</a></li>
                            <li><a href="cart.html">Cart</a></li>
                            <li><a href="checkout.html">Checkout</a></li>
                            <li><a href="track-order.html">Track Order</a></li>
                            <li><a href="wishlist.html">Wishlist</a></li>
                            <li><a href="faq.html">Faq</a></li>
                            <li><a href="login.html">Login</a></li>
                            <li><a href="register.html">Register</a></li>
                            <li><a href="policy.html">Policy</a></li>
                        </ul>
                    </li>
                    <li class="dropdown drop-list">
                        <span class="menu-toggle"></span>
                        <a href="javascript:void(0)" class="dropdown-list">Blog</a>
                        <ul class="sub-menu">
                            
                            <li><a href="blog-full-width.html">Blogs</a></li>
                            
                            <li><a href="blog-detail-full-width.html">Blog-detail</a></li>
                        </ul>
                    </li>
                    <li class="dropdown drop-list">
                        <span class="menu-toggle"></span>
                        <a href="javascript:void(0)">Element</a>
                        <ul class="sub-menu">
                            <li><a href="elements-products.html">Products</a></li>
                            <li><a href="elements-typography.html">Typography</a></li>
                            <li><a href="elements-buttons.html">Buttons</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Breadcrumb -->
    <section class="section-breadcrumb">
        <div class="cr-breadcrumb-image">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="cr-breadcrumb-title">
                            <h2>Blog Classic</h2>
                            <span><a href="index.html">Home</a> - Blog Classic</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Blog-Classic -->
    <section class="section-blog-Classic padding-tb-100">
        <div class="container">
            <div class="row mb-minus-24">
                <div class="col-lg-6 mb-24">
                    {% for article in articles  %}
                    
                    <div class="cr-blog-classic" data-aos="fade-up" data-aos-duration="2000" data-aos-delay="400">
                        <div class="cr-blog-classic-content">
                            <div class="cr-comment">
                                <span>{{article.author.user.username}} <code> / {{article.created}}</code></span>
                            </div>
                            <h4>{{article.title}}</h4>
                            <p>{{article.description}}</p>
                            <a href="{% url 'articles:blog-detail' id=article.id %}">read more</a>
                        </div>
                    
                        
                        <div class="cr-blog-image">
                            <img src="{{article.image.url}}" alt="blog-1">
                        </div>
                        
                    </div>
                    {% endfor %}
                   
                </div>
               
            </div>
            <nav aria-label="..." class="cr-pagination">
                <ul class="pagination">
                    {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page.previous_page_number}}">Previous</a>
                        
                    </li>
                    {% else %}
                    
                    <li class="page-item disabled">
                        <span class="page-link">Prev</span>
                    </li>
                    {% endif %}
                    {% for page_number in paginator.page_range  %}
                    
                    <li class="page-item {% if page_number == page.number %}active{% endif %}"><a class="page-link" href="?page={{page_number}}">{{page_number}}</a></li>
                    {% endfor %}

                    {% if page.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{page.next_page_number}}">Next</a>
                      
                  </li>
                  {% else %}
                  <li class="page-item disable">
                      <span class="page-link">Next</span>
                  </li>
                      {% endif %}
                </ul>
            </nav>
        </div>
    </section>


{% endblock main %}